Feature/fulldialog
Blogbotana/TelegramServerBot pull request #4
Opened 2022-06-27 17:52 UTC by Blogbotana

2022-06-27 18:33 UTC, destros52 commented on TelegramBot/TelegramBot/CallbackHandler.cs
> +                        //await TGBot.MyBot.BotClient.DeleteMessageAsync(query.From.Id, lastmessage.MessageId, TGBot.MyBot.CancellToket);
remove

2022-06-27 18:33 UTC, destros52 commented on TelegramBot/TelegramBot/DialogFunction.cs
> +            string enum1 = "UserButtonsMainMenu.";
magic word

2022-06-27 18:33 UTC, destros52 commented on TelegramBot/TelegramBot/TGBot.cs
> +                // UpdateType.Unknown:
remove

2022-06-27 18:33 UTC, destros52 commented on TelegramBot/TelegramBot/TGBot.cs
> +                // UpdateType.ChannelPost:
remove

2022-07-02 18:43 UTC, destros52 requested changes

2022-07-02 18:43 UTC, destros52 commented on TelegramBot/TelegramBot/DialogFunction.cs
> +            string enum1 = "UserButtonsMainMenu.";
still here

2022-07-02 18:44 UTC, Blogbotana commented on TelegramBot/TelegramBot/DialogFunction.cs
> +            string enum1 = "UserButtonsMainMenu.";
![image](https://user-images.githubusercontent.com/69924139/177012794-5539c5f5-a4e5-4c7c-8ccd-a4e4720158d2.png)

2022-07-02 18:55 UTC, destros52 approved these changes

2022-07-02 18:57 UTC, merged